### ISSUE TITLE
[Bug] Different country localizations for Paywall Products in TestFlight

### ISSUE THREAD

**Issue by ChristianSko** [FlineDev/FreemiumKit#3]
## Steps to Reproduce:
1. Configure the paywall using Freemiumkit.
2. Test the paywall on Testflight in Spanish.
3. Observe that the products contain different languages, including Spanish (the same behavior occurs for English). Have not yet tested other languages.

## Expected Behavior:
The language of the products should match the language of the device, which is currently set to Spanish.

## Current Behavior:
The paywall products contain a mix of languages, including Portuguese, Finnish, and Greek (see the attached image for reference). The translations set in App Store Connect do not match the displayed languages.

Greek -> "Ετησίως" (which means "Annually")
Finnish -> "Elinkikä" (which means "Lifetime")
Portuguese -> "Mensal" (meaning "Monthly")

## Environment:
- iOS 18, iPhone 15 Pro on Testflight
- Language and region set to Spain
-  Spanish Apple ID
- App language set to Spanish
- App localized in 27 languages
- It's possible that I'm configuring something incorrectly, but my understanding is that the localizations set in App Store Connect are what should appear on the product.

<img width="496" alt="image" src="https://github.com/user-attachments/assets/b9b681d8-01ba-4e34-8b9f-18422271d4b8">
<img width="937" alt="image" src="https://github.com/user-attachments/assets/258c3285-6b98-42f5-8313-502f78c884da">
<img width="932" alt="image" src="https://github.com/user-attachments/assets/3ea6b7f9-29d3-4572-bf49-a07c9551bc61">
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/4e414834-aa58-436b-877e-9a0aeddd245a">

**Comment by ChristianSko** [comment]
I have updated the localizations on my end in App Store Connect, which seems to have resolved the issue for the most part. It was likely an error on my end during the setup process.

However, the option to leave open-ended subscriptions with lifetime payments does not appear to be localized, so leaving this open for now!

![IMG_7BAB1738ADB8-1](https://github.com/user-attachments/assets/497082c1-cdb8-4fa1-ba77-27beb2473eae)

**Comment by Jeehut** [comment]
@ChristianSko Thank you for reporting this. Just to be sure there are no misunderstandings, do I get the following right?

1. You did not create the products (Monthly, Yearly, Lifetime) within FreemiumKit but manually on App Store Connect
2. You localized the subscriptions and in-app purchases also manually on Connect (not using FreemiumKit)
3. And when you did it manually, you misconfigured something there, FreemiumKit did not do any wrong language matching
4. Your last screenshot has the issue the it still states "one-time" in English and also "and" between terms/privacy

If I understand correctly, I just need to investigate and fix the "one-time" and "and" words in the SDK, right? Let me double-check right away…

**Comment by Jeehut** [comment]
You were totally right, I had missed to adjust my `Text` views to refer to the bundle module, so the localization lookup failed. I fixed it though in v1.7.1 – please update and it should be fixed! 🎉 

Here's the fixing commit, in case you're curious:
<img width="986" alt="Bildschirmfoto 2024-08-23 um 14 40 12" src="https://github.com/user-attachments/assets/053b8d1c-ffbb-4859-a97b-3779342c7ea5">

Thank you for reporting this! Let me know if you run into any other issues.

**Comment by ChristianSko** [comment]
Thanks,@Jeehut! I can confirm that the fix worked perfectly. I really appreciate your quick response and the helpful insight 🫡

Excited to see how your product evolves! I’ve just submitted my first paywall for review🚀😄

**Comment by ChristianSko** [comment]
@Jeehut, I'm having trouble getting my app's paywall approved by Apple. They've rejected it three times for the same reason (see attached image). The rejection message seems vague, and I initially thought it was about the EULA and privacy policy links, but those appear to be correct.

I now suspect the issue might be that the paywall functionality I'm proposing is too generic for my specific app.

I've seen that FreeiumKit will soon support custom features. Do you have an estimated timeline on that update? Alternatively, is there a way to use FreeiumKit to address Apple's rejection, or any workaround you can suggest?

<img width="703" alt="image" src="https://github.com/user-attachments/assets/31d6584a-fda0-498b-9f2f-0619baa7b89d">

**Comment by Jeehut** [comment]
@ChristianSko I can't give you a specific ETA on the custom features at this time. But nowhere in your rejection they mention that the listed features is the problem (correct me if I'm wrong). FYI: I got 3 apps approved that just use "Unlimited" and "Support Indie Developer" – that's totally enough.

They clearly state that you're missing a privacy and or EULA link either in the app or the app description. You see, you have to have a link to both in your app, AND in the app's metadata. The EULA needs to be in the App Description (for all languages you support on Connect) and also in the Privacy field.

If you are sure you have them all, answer exactly listing where you have them in the metadata and in your app and ask for a screenshot or description where they are missing it. Please note that I personally always add a link to both in my app settings screen instead of the paywall. In my paywall, I don't even link to Privacy/Terms. Maybe it's a requirement that you can access those links even after making a purchase, so that might be the issue if you only have them in the paywall.

I hope this helps. Let me know how it's going. Of course, I'll do anything to avoid app rejection due to FreemiumKit, so if it's really the features list, I'll make sure to add it quickly.

**Comment by ChristianSko** [comment]
@Jeehut, really appreciate your speedy reply and all the specifics you provided! 
Totally get it about the ETA, don't worry about that.

Actually you nailed it, it looks like I overlooked adding links to the metadata descriptions in some of my languages! 😅 The app's been given the green light and the paywall's finally live on Prod! 🥳 Thanks a bunch for all your help!

**Comment by Jeehut** [comment]
@ChristianSko Glad I could be of help! Congrats on the launch. 🥳
