### ISSUE TITLE
[Bug] Redeem code modal not showing  textfield to submit a code

### ISSUE THREAD

**Issue by ChristianSko** [FlineDev/FreemiumKit#6]
## Steps to Reproduce:
1. Launch the Paywall somehow.
2. Tap the "Redeem Code" button in the bottom left corner.

## Expected Behavior:
The user should be able to enter a promo code in the modal.

## Current Behavior:
A modal view appears, but no text field is available to enter any type of promo code.

## Environment:
iOS Simulator running iOS 18.

## Notes  
I might be wrong, as I'm not really familiar with promo codes, but I recently looked into creating some and didn't find a way to add them in any manner via simulator. Please let me know if I'm wrong 😄

<img width="559" alt="image" src="https://github.com/user-attachments/assets/b12aa012-44d1-4353-8e4d-da8001cb9eae">

**Comment by Jeehut** [comment]
As you can see by the text down below, you are in the `Xcode` environment, which means you're using a StoreKit Configuration file to test purchases right within Xcode instead of touching the App Store. That's why you can't enter a promo code. Simply change the scheme setting back to "None" like this and it should work in Simulator:
<img width="522" alt="Screenshot 2024-10-23 at 09 40 52" src="https://github.com/user-attachments/assets/049ede8f-1b7e-4b13-8c11-993317ac4309">

**Comment by ChristianSko** [comment]
Thanks, @Jeehut ! That really did the trick 😄 I appreciate your speedy response! 🚀 🙏

**Comment by Jeehut** [comment]
@ChristianSko You're welcome! 😊 Happy to help.
